services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db-bank
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_banco
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./banking_database/sql:/docker-entrypoint-initdb.d
    networks:
      - jbor-network

  customer-service:
    build: ./banking_backend/customer-service
    container_name: customer-service
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - jbor-network
    depends_on:
      - mysql
      
  account-service:
    build: ./banking_backend/account-service
    container_name: account-service
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - jbor-network
    depends_on:
      - customer-service
      


volumes:
  mysql-data:

networks:
  jbor-network: